// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHw_GmW7mPEFsN5sdziBurLjolb-A7WJc',
    appId: '1:859363908841:web:e57dceeec80f40f4e7e478',
    messagingSenderId: '859363908841',
    projectId: 'crud-api-79a1d',
    authDomain: 'crud-api-79a1d.firebaseapp.com',
    storageBucket: 'crud-api-79a1d.appspot.com',
    measurementId: 'G-2KDZR45KV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtODuKvViK2ehzvuqtRdcqN5jZY2qrgcE',
    appId: '1:859363908841:android:d95fc42bd7433d16e7e478',
    messagingSenderId: '859363908841',
    projectId: 'crud-api-79a1d',
    storageBucket: 'crud-api-79a1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKvD8z6nAtHI7KPwykLO6jGz2mGn1kK1k',
    appId: '1:859363908841:ios:f29882fcf47492a9e7e478',
    messagingSenderId: '859363908841',
    projectId: 'crud-api-79a1d',
    storageBucket: 'crud-api-79a1d.appspot.com',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKvD8z6nAtHI7KPwykLO6jGz2mGn1kK1k',
    appId: '1:859363908841:ios:f29882fcf47492a9e7e478',
    messagingSenderId: '859363908841',
    projectId: 'crud-api-79a1d',
    storageBucket: 'crud-api-79a1d.appspot.com',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHw_GmW7mPEFsN5sdziBurLjolb-A7WJc',
    appId: '1:859363908841:web:0302464d90b39ae5e7e478',
    messagingSenderId: '859363908841',
    projectId: 'crud-api-79a1d',
    authDomain: 'crud-api-79a1d.firebaseapp.com',
    storageBucket: 'crud-api-79a1d.appspot.com',
    measurementId: 'G-KYKKDCLY4E',
);
}